export const categories = [
    "Electronics",
    "Furniture",
    "Clothing",
    "Books",
    "Sports Equipment",
    "Home Appliances",
    "Jewelry",
    "Toys",
    "Automotive",
    "Art & Collectibles",
    "Musical Instruments",
    "Office Supplies",
    "Health & Beauty",
    "Baby Products",
    "Pet Supplies",
    "Gardening Tools",
    "Kitchenware",
    "Antiques",
    "Video Games",
    "Movies & Music",
    "Fitness Equipment",
    "Camping Gear",
    "Photography",
    "Crafts",
    "Party Supplies",
    "Industrial Equipment",
    "Building Materials",
    "Food & Beverages",
    "Tickets",
    "Services"
];